language: go
go:
  - 1.7
  - tip
install:
  - go get github.com/mattn/goveralls
script:
  - make
  - make test
  - make test_cover_submit
  - ./remap_coverage.sh
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
